apiVersion: v1
kind: Service
metadata:
  name: {{ include "consul-backup-s3.fullname" . }}
  labels:
    {{- include "consul-backup-s3.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "consul-backup-s3.selectorLabels" . | nindent 4 }}
